on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Leave it blank'
        # Default value if no value is explicitly provided
        default: 'N/A'
        # Input has to be provided for the workflow to run
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create README.md
      uses: actions-js/profile-readme@master
      with:
        username: Zorono
        github_token: ${{ secrets.GITHUB_TOKEN }}
        template: ./TEMPLATE.md # default is ./TEMPLATE.md
        readme: ./README.md # default is ./README.md
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
